/**
 * paths.ts — single source of truth for source/artefact file locations.
 *
 * Anything under src/ is a hand-edited source. Anything under dist/ is
 * a build artefact regenerated by `pnpm build`. The deploy step ships
 * the contents of dist/ + site/ to branding.n3ary.com.
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.resolve(here, '..');

export const PATHS = {
  srcLogoDir: path.join(ROOT, 'src', 'logo'),
  srcSocialDir: path.join(ROOT, 'src', 'social'),
  distDir: path.join(ROOT, 'dist'),
  siteDir: path.join(ROOT, 'site'),
} as const;

export const PRIMARY_LOGO = path.join(PATHS.srcLogoDir, 'neary-logo.svg');
export const SOCIAL_PREVIEW_SVG = path.join(PATHS.srcSocialDir, 'social-preview.svg');

/** PNG export sizes, named for the platforms that ask for them. */
export const PNG_SIZES = [16, 32, 64, 128, 180, 192, 256, 512, 1024] as const;

/** Social preview is a fixed GitHub-favoured aspect (1280×640). */
export const SOCIAL_PREVIEW = { width: 1280, height: 640 } as const;
